# Generated by Django 5.2.1 on 2025-05-25 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parent',
            old_name='name',
            new_name='first_name',
        ),
        migrations.AddField(
            model_name='parent',
            name='last_name',
            field=models.CharField(db_index=True, default='parent', max_length=100),
            preserve_default=False,
        ),
    ]
