# Generated by Django 5.2.1 on 2025-05-25 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parent',
            name='name',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterModelTable(
            name='parent',
            table='parents',
        ),
    ]
