# Generated by Django 5.2.1 on 2025-05-25 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school_app', '0002_alter_parent_name_alter_parent_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='parent',
            table='students_guardians',
        ),
    ]
