# Generated by Django 5.2.1 on 2025-05-31 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_app', '0003_subject_attendance_fee_result'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='roll_number',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
